gcp-auth = [
  "com.auth0:java-jwt:4.5.2"
  "com.github.jwt-scala::jwt-circe:11.0.4"
  "com.permutive::refreshable:2.1.1"
  "org.http4s::http4s-circe:0.23.34"
  "org.http4s::http4s-client:0.23.34"
  "com.alejandrohdezma::http4s-munit:2.0.0:test"
]

gcp-auth-pureconfig = [
  "com.github.pureconfig::pureconfig-core:0.17.10"
  "com.alejandrohdezma::http4s-munit:2.0.0:test"
]
